apiVersion: v2
name: argocd
description: ArgoCD Helm Chart
type: application
version: 0.1.0
appVersion: "2.9.3"

dependencies:
  - name: argo-cd
    version: 8.1.3
    repository: https://argoproj.github.io/argo-helm
